// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Menus
{

    internal class Menu
    {

        [JsonProperty("Id")]
        public int Id { get; set; }

        [JsonProperty("RestaurantId")]
        public int RestaurantId { get; set; }

        [JsonProperty("Title")]
        public string Title { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("Type")]
        public Type Type { get; set; }

        [JsonProperty("PickupOrDeliveryTime")]
        public PickupOrDeliveryTime PickupOrDeliveryTime { get; set; }

        [JsonProperty("AvailableDuring")]
        public AvailableDuring AvailableDuring { get; set; }

        [JsonProperty("DeliveryCostBelowThreshold")]
        public double DeliveryCostBelowThreshold { get; set; }

        [JsonProperty("DeliveryCostAboveThreshold")]
        public double DeliveryCostAboveThreshold { get; set; }

        [JsonProperty("DeliveryThresholdOrderAmount")]
        public double DeliveryThresholdOrderAmount { get; set; }

        [JsonProperty("ClosingWorkTime")]
        public string ClosingWorkTime { get; set; }

        [JsonProperty("DeliveryCostExamples")]
        public object DeliveryCostExamples { get; set; }

        [JsonProperty("CustomerReviewsSummary")]
        public object CustomerReviewsSummary { get; set; }

        [JsonProperty("Categories")]
        public object Categories { get; set; }

        [JsonProperty("Products")]
        public object Products { get; set; }
    }

}
