// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Menus
{

    internal class Tuesday
    {

        [JsonProperty("OpeningTime")]
        public string OpeningTime { get; set; }

        [JsonProperty("ClosingTime")]
        public string ClosingTime { get; set; }

        [JsonProperty("Status")]
        public int Status { get; set; }
    }

}
