// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Menus
{

    internal class SampleResponse1
    {

        [JsonProperty("Categories")]
        public Category[] Categories { get; set; }
    }

}
