// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example
{

    internal class SampleResponse1
    {

        [JsonProperty("ShortResultText")]
        public string ShortResultText { get; set; }

        [JsonProperty("Restaurants")]
        public Restaurant[] Restaurants { get; set; }
    }

}
